# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Morsa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.0.0'
  pod 'AudioKit', '~> 3.7'

  target 'MorsaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MorsaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
